package com.tunasrent.auctionapps.taksasi;

import android.annotation.SuppressLint;
import android.app.ProgressDialog;
import android.content.Intent;
import android.graphics.Color;
import android.os.AsyncTask;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.MenuItem;
import android.view.View;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.tunasrent.auctionapps.R;
import com.tunasrent.auctionapps.bp.BpCekCeklistActivity;
import com.tunasrent.auctionapps.bp.BpCekFormActivity;
import com.tunasrent.auctionapps.util.RequestHandler;
import com.tunasrent.auctionapps.util.UserSessionManager;
import com.tunasrent.auctionapps.util.configuration;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.HashMap;

public class TaksasiCekFormActivity extends AppCompatActivity {
    private String appid = configuration.APPID;
    private String ccode = configuration.CCODE;
    int code;
    String message;
    Toolbar toolbar;
    Button btnNext;

    String _name;
    String _fullname;
    String _appid;
    String _ccode;
    String _token;
    String _group;
    JSONArray result;
    String nopol;

    UserSessionManager session;
    EditText etTanggal;
    EditText etPukul;
    EditText etLokasi_penarikan;
    EditText etMerk;
    EditText etTahun;
    EditText etStnk_an;
    EditText etNopol1;
    EditText etNopol2;
    EditText etNopol3;
    EditText etKmditarik;
    EditText etMeterbensin;
    EditText etCabang;
    EditText etNomesin;
    EditText etNorangka;
    EditText etWarna;
    EditText etKmditerima;
    EditText etLokasipool;
    EditText etTypeunit;

    String vehicle_id;
    String vhc_type_id;
    String vhc_type_name;
    String vehicle_year;
    String vehicle_color;
    String vehicle_engine_no;
    String vehicle_chasis_no;
    String vhc_loc_penarikan;
    String vhc_loc_pool;
    String vhc_date_in;
    String vhc_stnk;
    String vhc_kmditarik;
    String vhc_kmditerima;
    String vhc_meterbensin;
    String vhc_cabang;
    String vendor_name;
    String pool;
    String vhc_cat_name;


    int var_cbGrill1_fisikmuka=0;
    int var_cbGrill2_fisikmuka = 0;
    int var_cbLampu1_fisikmuka=0;
    int var_cbLampu2_fisikmuka = 0;
    int var_cbLampusen1_fisikmuka=0;
    int var_cbLampusen2_fisikmuka = 0;
    int var_cbBamper1_fisikmuka=0;
    int var_cbBamper2_fisikmuka = 0;
    int var_cbEmblem1_fisikmuka=0;
    int var_cbEmblem2_fisikmuka = 0;
    int var_cbTanduk1_fisikmuka=0;
    int var_cbTanduk2_fisikmuka = 0;

    int var_cbFootstep1_fisikkiri=0;
    int var_cbFootstep2_fisikkiri=0;
    int var_cbPintudpn1_fisikkiri=0;
    int var_cbPintudpn2_fisikkiri=0;
    int var_cbPintublk1_fisikkiri=0;
    int var_cbPintublk2_fisikkiri=0;
    int var_cbBamper1_fisikkiri=0;
    int var_cbBamper2_fisikkiri=0;
    int var_cbFenderblk1_fisikkiri=0;
    int var_cbFenderblk2_fisikkiri=0;
    int var_cbSpion1_fisikkiri=0;
    int var_cbSpion2_fisikkiri=0;
    int var_cbEmblem1_fisikkiri=0;
    int var_cbEmblem2_fisikkiri=0;
    int var_rbBan_fisikkiri=0;
    int var_cbBan1_fisikkiri=0;
    int var_cbBan2_fisikkiri=0;
    int var_spBan2_fisikkiri;
    int var_vspBan2_fisikkiri =0;
    int var_rbVelgstandard_fisikkiri=0;
    int var_rbVelgracing_fisikkiri=0;
    int var_cbVelg1_fisikkiri=0;
    int var_cbVelg2_fisikkiri=0;
    int var_cbDop1_fisikkiri=0;
    int var_cbDop2_fisikkiri=0;
    int var_cbDopBlk1_fisikkiri=0;
    int var_cbDopBlk2_fisikkiri=0;

    int var_cbSpoiler1_fisikblkg=0;
    int var_cbSpoiler2_fisikblkg=0;
    int var_cbLampu1_fisikblkg=0;
    int var_cbLampu2_fisikblkg=0;
    int var_cbLampusen1_fisikblkg=0;
    int var_cbLampusen2_fisikblkg=0;
    int var_cbBamper1_fisikblkg=0;
    int var_cbBamper2_fisikblkg=0;
    int var_cbEmblem1_fisikblkg=0;
    int var_cbEmblem2_fisikblkg=0;
    int var_cbKnalpot1_fisikblkg=0;
    int var_cbKnalpot2_fisikblkg=0;

    int var_cbFoot1_fisikkanan=0;
    int var_cbFoot2_fisikkanan=0;
    int var_cbPintudpn1_fisikkanan=0;
    int var_cbPintudpn2_fisikkanan=0;
    int var_cbPintublk1_fisikkanan=0;
    int var_cbPintublk2_fisikkanan=0;
    int var_cbBamper1_fisikkanan=0;
    int var_cbBamper2_fisikkanan=0;
    int var_cbFenderblk1_fisikkanan=0;
    int var_cbFenderblk2_fisikkanan=0;
    int var_cbSpion1_fisikkanan=0;
    int var_cbSpion2_fisikkanan=0;
    int var_cbEmblem1_fisikkanan=0;
    int var_cbEmblem2_fisikkanan=0;
    int var_rbBan_fisikkanan=0;
    int var_cbBan1_fisikkanan=0;
    int var_cbBan2_fisikkanan=0;
    int var_cbVelg1_fisikkanan=0;
    int var_cbVelg2_fisikkanan=0;
    int var_cbDop1_fisikkanan=0;
    int var_cbDop2_fisikkanan=0;
    int var_cbDopBlk1_fisikkanan=0;
    int var_cbDopBlk2_fisikkanan=0;
    int var_cbKunciktk1_perlengkapan=0;
    int var_cbKunciktk2_perlengkapan=0;
    int var_cbSpion1_perlengkapan=0;
    int var_cbSpion2_perlengkapan=0;
    int var_cbJok1_perlengkapan=0;
    int var_cbJok2_perlengkapan=0;
    int var_cbSarung1_perlengkapan=0;
    int var_cbSarung2_perlengkapan=0;
    int var_cbSandaran1_perlengkapan=0;
    int var_cbSandaran2_perlengkapan=0;
    int var_cbKarpet1_perlengkapan=0;
    int var_cbKarpet2_perlengkapan=0;
    int var_cbPelindung1_perlengkapan=0;
    int var_cbPelindung2_perlengkapan=0;
    int var_cbSegitiga1_perlengkapan=0;
    int var_cbSegitiga2_perlengkapan=0;
    int var_cbTool1_perlengkapan=0;
    int var_cbTool2_perlengkapan=0;
    int var_cbCadangan1_perlengkapan=0;
    int var_cbCadangan2_perlengkapan=0;
    int var_cbKunciban1_perlengkapan=0;
    int var_cbKunciban2_perlengkapan=0;
    int var_cbDongkrak1_perlengkapan=0;
    int var_cbDongkrak2_perlengkapan=0;
    int var_cbAntena1_perlengkapan=0;
    int var_cbAntena2_perlengkapan=0;
    int var_cbAirbag1_perlengkapan=0;
    int var_cbAirbag2_perlengkapan=0;

    int var_cbLampukbt1_listrik=0;
    int var_cbLampukbt2_listrik=0;
    int var_cbWiperkacadpn1_listrik=0;
    int var_cbWiperkacadpn2_listrik=0;
    int var_cbWiperkacablk1_listrik=0;
    int var_cbWiperkacablk2_listrik=0;
    int var_cbKlakson1_listrik=0;
    int var_cbKlakson2_listrik=0;
    int var_cbAlarm1_listrik=0;
    int var_cbAlarm2_listrik=0;
    int var_cbJam1_listrik=0;
    int var_cbJam2_listrik=0;
    int var_cbLighter1_listrik=0;
    int var_cbLighter2_listrik=0;
    int var_rbRadio_listrik=0;
    int var_cbRadio1_listrik=0;
    int var_cbRadio2_listrik=0;
    int var_cbPowersup1_listrik=0;
    int var_cbPowersup2_listrik=0;
    int var_cbSpeaker1_listrik=0;
    int var_cbSpeaker2_listrik=0;
    int var_cbAc1_listrik=0;
    int var_cbAc2_listrik=0;
    int var_cbPowerwin1_listrik=0;
    int var_cbPowerwin2_listrik=0;
    int var_cbCentral1_listrik=0;
    int var_cbCentral2_listrik=0;
    int var_cbRemote1_listrik=0;
    int var_cbRemote2_listrik=0;
    int var_cbSpeedo1_listrik=0;
    int var_cbSpeedo2_listrik=0;
    int var_cbOdometer1_listrik=0;
    int var_cbOdometer2_listrik=0;
    int var_cbTacho1_listrik=0;
    int var_cbTacho2_listrik=0;
    int var_cbAccu1_listrik=0;
    int var_cbAccu2_listrik=0;

    int var_cbMesin1_lain=0;
    int var_cbMesin2_lain=0;
    int var_cbHidraulik1_lain=0;
    int var_cbHidraulik2_lain=0;
    int var_cbGardan1_lain=0;
    int var_cbGardan2_lain=0;
    int var_cbAs1_lain=0;
    int var_cbAs2_lain=0;
    int var_cbBak1_lain=0;
    int var_cbBak2_lain=0;
    int var_cbStnk1_lain=0;
    int var_cbStnk2_lain=0;
    String var_etStnk;
    int var_cbBukukir1_lain=0;
    int var_cbBukukir2_lain=0;
    String var_etBukukir;
    int var_cbTrayek1_lain=0;
    int var_cbTrayek2_lain=0;
    String var_etTrayek;
    int var_cbUsaha1_lain=0;
    int var_cbUsaha2_lain=0;
    String var_etUsaha;
    int var_cbBukumnl1_lain=0;
    int var_cbBukumnl2_lain=0;

    String var_picPenarikanDiterima;
    String var_picPenarikan;
    String var_picPenyimpanan;
    String var_picPenjualan;
    String var_picpengiriman;

    String var_note_picpenarikan;
    String var_note_picpenyimpanan;
    String var_note_picpengiriman;

    String var_img1;
    String var_img2;
    String var_img3;
    String var_img4;
    String var_img5;
    String var_img6;
    String var_img7;
    String var_img8;
    String var_img9;
    String var_img10;
    String var_img11;
    String var_img12;
    String var_img13;
    String var_img14;
    AutoCompleteTextView etVendor;

    int var_cover_kepala1 = 0;
    int var_cover_kepala2 = 0;
    int var_cover_speedo1 = 0;
    int var_cover_speedo2 = 0;
    int var_cover_depan1 = 0;
    int var_cover_depan2 = 0;
    int var_sayap_kanan1 = 0;
    int var_sayap_kanan2 = 0;
    int var_sayap_kiri1 = 0;
    int var_sayap_kiri2 = 0;
    int var_spak_depan1 = 0;
    int var_spak_depan2 = 0;
    int var_cover_tengah1 = 0;
    int var_cover_tengah2 = 0;
    int var_cover_spgkanan1 = 0;
    int var_cover_spgkanan2 = 0;
    int var_cover_spgkiri1 = 0;
    int var_cover_spgkiri2 = 0;
    int var_rantai_depan1 = 0;
    int var_rantai_depan2 = 0;
    int var_rantai_blkg1 = 0;
    int var_rantai_blkg2 = 0;
    int var_spak_blkg1 = 0;
    int var_spak_blkg2 = 0;
    int var_cover_accu1 = 0;
    int var_cover_accu2 = 0;
    int var_cover_lampurem1 = 0;
    int var_cover_lampurem2 = 0;
    int var_tangki_bensin1 = 0;
    int var_tangki_bensin2 = 0;
    int var_cover_bawah1 = 0;
    int var_cover_bawah2 = 0;
    int var_dek_desk1 = 0;
    int var_dek_desk2 = 0;
    int var_cover_mesin1 = 0;
    int var_cover_mesin2 = 0;
    int var_emblem1 = 0;
    int var_emblem2 = 0;

    int var_blok_mesin1 = 0;
    int var_blok_mesin2 = 0;
    int var_carburator1 = 0;
    int var_carburator2 = 0;
    int var_filter_carbu1 = 0;
    int var_filter_carbu2 = 0;
    int var_busi1 = 0;
    int var_busi2 = 0;
    int var_cdi1 = 0;
    int var_cdi2 = 0;
    int var_accu1 = 0;
    int var_accu2 = 0;
    int var_kick_starter1 = 0;
    int var_kick_starter2 = 0;
    int var_perseneling1 = 0;
    int var_perseneling2 = 0;
    int var_knalpot1 = 0;
    int var_knalpot2 = 0;
    int var_coil1 = 0;
    int var_coil2 = 0;
    int var_blok1 = 0;
    int var_blok2 = 0;
    int var_tutupcvt1 = 0;
    int var_tutupcvt2 = 0;
    int var_radiator1 = 0;
    int var_radiator2 = 0;
    int var_lampu_depan1 = 0;
    int var_lampu_depan2 = 0;
    int var_sein_depan1 = 0;
    int var_sein_depan2 = 0;
    int var_sein_blkg1 = 0;
    int var_sein_blkg2 = 0;
    int var_lampu_rem1 = 0;
    int var_lampu_rem2 = 0;

    int var_handlerem_depan1 = 0;
    int var_handlerem_depan2 = 0;
    int var_pedalrem_blkg1 = 0;
    int var_pedalrem_blkg2 = 0;
    int var_handlerem_blkg1 = 0;
    int var_handlerem_blkg2 = 0;
    int var_handle_kopling1 = 0;
    int var_handle_kopling2 = 0;
    int var_master_rem1 = 0;
    int var_master_rem2 = 0;
    int var_caliper1 = 0;
    int var_caliper2 = 0;
    int var_cakram1 = 0;
    int var_cakram2 = 0;
    int var_shock_depan1 = 0;
    int var_shock_depan2 = 0;
    int var_shock_blkg1 = 0;
    int var_shock_blkg2 = 0;
    int var_tromol_depan1 = 0;
    int var_tromol_depan2 = 0;
    int var_tromol_blkg1 = 0;
    int var_tromol_blkg2 = 0;
    int var_footstep_depan1 = 0;
    int var_footstep_depan2 = 0;
    int var_footstep_blkg1 = 0;
    int var_footstep_blkg2 = 0;
    int var_swing_arm1 = 0;
    int var_swing_arm2 = 0;
    int var_rantai_fanbelt1 = 0;
    int var_rantai_fanbelt2 = 0;
    int var_gear_depan1 = 0;
    int var_gear_depan2 = 0;
    int var_gear_blkg1 = 0;
    int var_gear_blkg2 = 0;
    int var_standar_tengah1 = 0;
    int var_standar_tengah2 = 0;
    int var_standar_samping1 = 0;
    int var_standar_samping2 = 0;
    int var_ban_depan1 = 0;
    int var_ban_depan2 = 0;
    int var_ban_blkg1 = 0;
    int var_ban_blkg2 = 0;
    int var_velg_depan1 = 0;
    int var_velg_depan2 = 0;
    int var_velg_blkg1 = 0;
    int var_velg_blkg2 = 0;

    int var_kaca_spion1 = 0;
    int var_kaca_spion2 = 0;
    int var_speedometer1 = 0;
    int var_speedometer2 = 0;
    int var_grip_stang1 = 0;
    int var_grip_stang2 = 0;
    int var_rumah_kunci1 = 0;
    int var_rumah_kunci2 = 0;
    int var_klakson1 = 0;
    int var_klakson2 = 0;
    int var_behel1 = 0;
    int var_behel2 = 0;
    int var_tutup_knalpot1 = 0;
    int var_tutup_knalpot2 = 0;
    int var_jok1 = 0;
    int var_jok2 = 0;
    int var_stripping1 = 0;
    int var_stripping2 = 0;
    int var_tombol_navigasi1 = 0;
    int var_tombol_navigasi2 = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_taksasi_cek_form);

        toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setTitle("Input Form");
        toolbar.setTitleTextColor(Color.WHITE);

        session = new UserSessionManager(getApplicationContext());
        HashMap<String, String> user = session.getUserDetails();
        _name = user.get(UserSessionManager.SES_NAME);
        _fullname = user.get(UserSessionManager.SES_FULLNAME);
        _appid = user.get(UserSessionManager.SES_APPID);
        _ccode = user.get(UserSessionManager.SES_CCODE);
        _token = user.get(UserSessionManager.SES_TOKEN);
        _group = user.get(UserSessionManager.SES_GROUP);

        Bundle b = getIntent().getExtras();
        if (b != null) {
            nopol = b.getString("parse_nopol");
        }

        etTanggal = findViewById(R.id.et_tanggal);
        etPukul = findViewById(R.id.et_pukul);
        etLokasi_penarikan = findViewById(R.id.et_lokasi_penarikan);
        etMerk = findViewById(R.id.et_merktype);
        etTahun = findViewById(R.id.et_tahun);
        etStnk_an = findViewById(R.id.et_stnk_an);
        etNopol1 = findViewById(R.id.et_nopol1);
        etNopol2 = findViewById(R.id.et_nopol2);
        etNopol3 = findViewById(R.id.et_nopol3);
        etKmditarik = findViewById(R.id.et_kmditarik);
        etMeterbensin = findViewById(R.id.et_meterbensin);
        etCabang = findViewById(R.id.et_cabang);
        etNomesin = findViewById(R.id.et_nomesin);
        etNorangka = findViewById(R.id.et_norangka);
        etWarna = findViewById(R.id.et_warna);
        etKmditerima = findViewById(R.id.et_kmditerima);
        etVendor = findViewById(R.id.et_vendor);
        etLokasipool = findViewById(R.id.et_lokasipool);
        etTypeunit = findViewById(R.id.et_typeunit);
        btnNext = findViewById(R.id.btn_next);

        getBastk();

        btnNext.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(vhc_cat_name.equals("MTR")) {
                    Intent i = new Intent(TaksasiCekFormActivity.this, TaksasiCekCeklistMotorActivity.class);
                    Bundle b = new Bundle();

                    b.putInt(configuration.MOBMOTOR_cover_kepala1, var_cover_kepala1);
                    b.putInt(configuration.MOBMOTOR_cover_kepala2, var_cover_kepala2);
                    b.putInt(configuration.MOBMOTOR_cover_speedo1, var_cover_speedo1);
                    b.putInt(configuration.MOBMOTOR_cover_speedo2, var_cover_speedo2);
                    b.putInt(configuration.MOBMOTOR_cover_depan1, var_cover_depan1);
                    b.putInt(configuration.MOBMOTOR_cover_depan2, var_cover_depan2);
                    b.putInt(configuration.MOBMOTOR_sayap_kanan1, var_sayap_kanan1);
                    b.putInt(configuration.MOBMOTOR_sayap_kanan2, var_sayap_kanan2);
                    b.putInt(configuration.MOBMOTOR_sayap_kiri1, var_sayap_kiri1);
                    b.putInt(configuration.MOBMOTOR_sayap_kiri2, var_sayap_kiri2);
                    b.putInt(configuration.MOBMOTOR_spak_depan1, var_spak_depan1);
                    b.putInt(configuration.MOBMOTOR_spak_depan2, var_spak_depan2);

                    b.putInt(configuration.MOBMOTOR_cover_tengah1, var_cover_tengah1);
                    b.putInt(configuration.MOBMOTOR_cover_tengah2, var_cover_tengah2);
                    b.putInt(configuration.MOBMOTOR_cover_spgkanan1, var_cover_spgkanan1);
                    b.putInt(configuration.MOBMOTOR_cover_spgkanan2, var_cover_spgkanan2);
                    b.putInt(configuration.MOBMOTOR_cover_spgkiri1, var_cover_spgkiri1);
                    b.putInt(configuration.MOBMOTOR_cover_spgkiri2, var_cover_spgkiri2);
                    b.putInt(configuration.MOBMOTOR_rantai_depan1, var_rantai_depan1);
                    b.putInt(configuration.MOBMOTOR_rantai_depan2, var_rantai_depan2);
                    b.putInt(configuration.MOBMOTOR_rantai_blkg1, var_rantai_blkg1);
                    b.putInt(configuration.MOBMOTOR_rantai_blkg2, var_rantai_blkg2);
                    b.putInt(configuration.MOBMOTOR_spak_blkg1, var_spak_blkg1);
                    b.putInt(configuration.MOBMOTOR_spak_blkg2, var_spak_blkg2);
                    b.putInt(configuration.MOBMOTOR_cover_accu1, var_cover_accu1);
                    b.putInt(configuration.MOBMOTOR_cover_accu2, var_cover_accu2);
                    b.putInt(configuration.MOBMOTOR_cover_lampurem1, var_cover_lampurem1);
                    b.putInt(configuration.MOBMOTOR_cover_lampurem2, var_cover_lampurem2);
                    b.putInt(configuration.MOBMOTOR_tangki_bensin1, var_tangki_bensin1);
                    b.putInt(configuration.MOBMOTOR_tangki_bensin2, var_tangki_bensin2);
                    b.putInt(configuration.MOBMOTOR_cover_bawah1, var_cover_bawah1);
                    b.putInt(configuration.MOBMOTOR_cover_bawah2, var_cover_bawah2);
                    b.putInt(configuration.MOBMOTOR_dek_desk1, var_dek_desk1);
                    b.putInt(configuration.MOBMOTOR_dek_desk2, var_dek_desk2);
                    b.putInt(configuration.MOBMOTOR_cover_mesin1, var_cover_mesin1);
                    b.putInt(configuration.MOBMOTOR_cover_mesin2, var_cover_mesin2);
                    b.putInt(configuration.MOBMOTOR_emblem1, var_emblem1);

                    b.putInt(configuration.MOBMOTOR_emblem2, var_emblem2);
                    b.putInt(configuration.MOBMOTOR_blok_mesin1, var_blok_mesin1);
                    b.putInt(configuration.MOBMOTOR_blok_mesin2, var_blok_mesin2);
                    b.putInt(configuration.MOBMOTOR_carburator1, var_carburator1);
                    b.putInt(configuration.MOBMOTOR_carburator2, var_carburator2);
                    b.putInt(configuration.MOBMOTOR_filter_carbu1, var_filter_carbu1);
                    b.putInt(configuration.MOBMOTOR_filter_carbu2, var_filter_carbu2);
                    b.putInt(configuration.MOBMOTOR_busi1, var_busi1);
                    b.putInt(configuration.MOBMOTOR_busi2, var_busi2);
                    b.putInt(configuration.MOBMOTOR_cdi1, var_cdi1);
                    b.putInt(configuration.MOBMOTOR_cdi2, var_cdi2);
                    b.putInt(configuration.MOBMOTOR_accu1, var_accu1);
                    b.putInt(configuration.MOBMOTOR_accu2, var_accu2);
                    b.putInt(configuration.MOBMOTOR_kick_starter1, var_kick_starter1);
                    b.putInt(configuration.MOBMOTOR_kick_starter2, var_kick_starter2);
                    b.putInt(configuration.MOBMOTOR_perseneling1, var_perseneling1);
                    b.putInt(configuration.MOBMOTOR_perseneling2, var_perseneling2);
                    b.putInt(configuration.MOBMOTOR_knalpot1, var_knalpot1);
                    b.putInt(configuration.MOBMOTOR_knalpot2, var_knalpot2);
                    b.putInt(configuration.MOBMOTOR_coil1, var_coil1);
                    b.putInt(configuration.MOBMOTOR_coil2, var_coil2);
                    b.putInt(configuration.MOBMOTOR_blok1, var_blok1);
                    b.putInt(configuration.MOBMOTOR_blok2, var_blok2);
                    b.putInt(configuration.MOBMOTOR_tutupcvt1, var_tutupcvt1);
                    b.putInt(configuration.MOBMOTOR_tutupcvt2, var_tutupcvt2);
                    b.putInt(configuration.MOBMOTOR_radiator1, var_radiator1);
                    b.putInt(configuration.MOBMOTOR_radiator2, var_radiator2);
                    b.putInt(configuration.MOBMOTOR_lampu_depan1, var_lampu_depan1);
                    b.putInt(configuration.MOBMOTOR_lampu_depan2, var_lampu_depan2);
                    b.putInt(configuration.MOBMOTOR_sein_depan1, var_sein_depan1);
                    b.putInt(configuration.MOBMOTOR_sein_depan2, var_sein_depan2);
                    b.putInt(configuration.MOBMOTOR_sein_blkg1, var_sein_blkg1);
                    b.putInt(configuration.MOBMOTOR_sein_blkg2, var_sein_blkg2);
                    b.putInt(configuration.MOBMOTOR_lampu_rem1, var_lampu_rem1);
                    b.putInt(configuration.MOBMOTOR_lampu_rem2, var_lampu_rem2);

                    b.putInt(configuration.MOBMOTOR_handlerem_depan1, var_handlerem_depan1);
                    b.putInt(configuration.MOBMOTOR_handlerem_depan2, var_handlerem_depan2);
                    b.putInt(configuration.MOBMOTOR_pedalrem_blkg1, var_pedalrem_blkg1);
                    b.putInt(configuration.MOBMOTOR_pedalrem_blkg2, var_pedalrem_blkg2);
                    b.putInt(configuration.MOBMOTOR_handlerem_blkg1, var_handlerem_blkg1);
                    b.putInt(configuration.MOBMOTOR_handlerem_blkg2, var_handlerem_blkg2);
                    b.putInt(configuration.MOBMOTOR_handle_kopling1, var_handle_kopling1);
                    b.putInt(configuration.MOBMOTOR_handle_kopling2, var_handle_kopling2);
                    b.putInt(configuration.MOBMOTOR_master_rem1, var_master_rem1);
                    b.putInt(configuration.MOBMOTOR_master_rem2, var_master_rem2);
                    b.putInt(configuration.MOBMOTOR_caliper1, var_caliper1);
                    b.putInt(configuration.MOBMOTOR_caliper2, var_caliper2);
                    b.putInt(configuration.MOBMOTOR_cakram1, var_cakram1);
                    b.putInt(configuration.MOBMOTOR_cakram2, var_cakram2);
                    b.putInt(configuration.MOBMOTOR_shock_depan1, var_shock_depan1);
                    b.putInt(configuration.MOBMOTOR_shock_depan2, var_shock_depan2);
                    b.putInt(configuration.MOBMOTOR_shock_blkg1, var_shock_blkg1);
                    b.putInt(configuration.MOBMOTOR_shock_blkg2, var_shock_blkg2);
                    b.putInt(configuration.MOBMOTOR_tromol_depan1, var_tromol_depan1);
                    b.putInt(configuration.MOBMOTOR_tromol_depan2, var_tromol_depan2);
                    b.putInt(configuration.MOBMOTOR_tromol_blkg1, var_tromol_blkg1);
                    b.putInt(configuration.MOBMOTOR_tromol_blkg2, var_tromol_blkg2);
                    b.putInt(configuration.MOBMOTOR_footstep_depan1, var_footstep_depan1);
                    b.putInt(configuration.MOBMOTOR_footstep_depan2, var_footstep_depan2);
                    b.putInt(configuration.MOBMOTOR_footstep_blkg1, var_footstep_blkg1);
                    b.putInt(configuration.MOBMOTOR_footstep_blkg2, var_footstep_blkg2);
                    b.putInt(configuration.MOBMOTOR_swing_arm1, var_swing_arm1);
                    b.putInt(configuration.MOBMOTOR_swing_arm2, var_swing_arm2);
                    b.putInt(configuration.MOBMOTOR_rantai_fanbelt1, var_rantai_fanbelt1);
                    b.putInt(configuration.MOBMOTOR_rantai_fanbelt2, var_rantai_fanbelt2);
                    b.putInt(configuration.MOBMOTOR_gear_depan1, var_gear_depan1);
                    b.putInt(configuration.MOBMOTOR_gear_depan2, var_gear_depan2);
                    b.putInt(configuration.MOBMOTOR_gear_blkg1, var_gear_blkg1);
                    b.putInt(configuration.MOBMOTOR_gear_blkg2, var_gear_blkg2);
                    b.putInt(configuration.MOBMOTOR_standar_tengah1, var_standar_tengah1);
                    b.putInt(configuration.MOBMOTOR_standar_tengah2, var_standar_tengah2);
                    b.putInt(configuration.MOBMOTOR_standar_samping1, var_standar_samping1);
                    b.putInt(configuration.MOBMOTOR_standar_samping2, var_standar_samping2);
                    b.putInt(configuration.MOBMOTOR_ban_depan1, var_ban_depan1);
                    b.putInt(configuration.MOBMOTOR_ban_depan2, var_ban_depan2);
                    b.putInt(configuration.MOBMOTOR_ban_blkg1, var_ban_blkg1);
                    b.putInt(configuration.MOBMOTOR_ban_blkg2, var_ban_blkg2);
                    b.putInt(configuration.MOBMOTOR_velg_depan1, var_velg_depan1);
                    b.putInt(configuration.MOBMOTOR_velg_depan2, var_velg_depan2);
                    b.putInt(configuration.MOBMOTOR_velg_blkg1, var_velg_blkg1);
                    b.putInt(configuration.MOBMOTOR_velg_blkg2, var_velg_blkg2);
                    b.putInt(configuration.MOBMOTOR_kaca_spion1, var_kaca_spion1);
                    b.putInt(configuration.MOBMOTOR_kaca_spion2, var_kaca_spion2);
                    b.putInt(configuration.MOBMOTOR_speedometer1, var_speedometer1);
                    b.putInt(configuration.MOBMOTOR_speedometer2, var_speedometer2);
                    b.putInt(configuration.MOBMOTOR_Grip_stang1, var_grip_stang1);
                    b.putInt(configuration.MOBMOTOR_Grip_stang2, var_grip_stang2);
                    b.putInt(configuration.MOBMOTOR_Rumah_kunci1, var_rumah_kunci1);
                    b.putInt(configuration.MOBMOTOR_Rumah_kunci2, var_rumah_kunci2);
                    b.putInt(configuration.MOBMOTOR_Klakson1, var_klakson1);
                    b.putInt(configuration.MOBMOTOR_Klakson2, var_klakson2);
                    b.putInt(configuration.MOBMOTOR_Behel1, var_behel1);
                    b.putInt(configuration.MOBMOTOR_Behel2, var_behel2);
                    b.putInt(configuration.MOBMOTOR_Tutup_knalpot1, var_tutup_knalpot1);
                    b.putInt(configuration.MOBMOTOR_Tutup_knalpot2, var_tutup_knalpot2);
                    b.putInt(configuration.MOBMOTOR_jok1, var_jok1);
                    b.putInt(configuration.MOBMOTOR_jok2, var_jok2);
                    b.putInt(configuration.MOBMOTOR_Stripping1, var_stripping1);
                    b.putInt(configuration.MOBMOTOR_Stripping2, var_stripping2);
                    b.putInt(configuration.MOBMOTOR_Tombol_navigasi1, var_tombol_navigasi1);
                    b.putInt(configuration.MOBMOTOR_Tombol_navigasi2, var_tombol_navigasi2);
                    b.putInt("stnk1_lain", var_cbStnk1_lain);
                    b.putInt("stnk2_lain", var_cbStnk2_lain);
                    b.putString("stnk_lain", var_etStnk);
                    b.putInt("bukumnl1_lain", var_cbBukumnl1_lain);
                    b.putInt("bukumnl2_lain", var_cbBukumnl2_lain);

                    b.putString("picpenarikan_diterima", var_picPenarikanDiterima);
                    b.putString("picpenarikan", var_picPenarikan);
                    b.putString("picpenyimpanan", var_picPenyimpanan);
                    b.putString("picpenjualan", var_picPenjualan);
                    b.putString("picpengiriman", var_picpengiriman);

                    b.putString("note_picpenarikan", var_note_picpenarikan);
                    b.putString("note_picpenyimpanan", var_note_picpenyimpanan);
                    b.putString("note_picpengiriman", var_note_picpengiriman);

                    b.putString("img1", var_img1);
                    b.putString("img2", var_img2);
                    b.putString("img3", var_img3);
                    b.putString("img4", var_img4);
                    b.putString("img5", var_img5);
                    b.putString("img6", var_img6);
                    b.putString("img7", var_img7);
                    b.putString("img8", var_img8);
                    b.putString("img9", var_img9);
                    b.putString("img10", var_img10);
                    b.putString("img11", var_img11);
                    b.putString("img12", var_img12);
                    b.putString("nopol",nopol);

                    i.putExtras(b);
                    startActivity(i);

                } else {
                    Intent i = new Intent(TaksasiCekFormActivity.this,TaksasiCekCeklistActivity.class);
                    Bundle b = new Bundle();
                    b.putInt("grill1_fisikmuka", var_cbGrill1_fisikmuka);
                    b.putInt("grill2_fisikmuka", var_cbGrill2_fisikmuka);
                    b.putInt("lampu1_fisikmuka", var_cbLampu1_fisikmuka);
                    b.putInt("lampu2_fisikmuka", var_cbLampu2_fisikmuka);
                    b.putInt("lampusen1_fisikmuka", var_cbLampusen1_fisikmuka);
                    b.putInt("lampusen2_fisikmuka", var_cbLampusen2_fisikmuka);
                    b.putInt("bamper1_fisikmuka", var_cbBamper1_fisikmuka);
                    b.putInt("bamper2_fisikmuka", var_cbBamper2_fisikmuka);
                    b.putInt("emblem1_fisikmuka", var_cbEmblem1_fisikmuka);
                    b.putInt("emblem2_fisikmuka", var_cbEmblem2_fisikmuka);
                    b.putInt("tanduk1_fisikmuka", var_cbTanduk1_fisikmuka);
                    b.putInt("tanduk2_fisikmuka", var_cbTanduk2_fisikmuka);

                    b.putInt("footstep1_fisikkiri", var_cbFootstep1_fisikkiri);
                    b.putInt("footstep2_fisikkiri", var_cbFootstep2_fisikkiri);
                    b.putInt("pintudpn1_fisikkiri", var_cbPintudpn1_fisikkiri);
                    b.putInt("pintudpn2_fisikkiri", var_cbPintudpn2_fisikkiri);
                    b.putInt("pintublk1_fisikkiri", var_cbPintublk1_fisikkiri);
                    b.putInt("pintublk2_fisikkiri", var_cbPintublk2_fisikkiri);
                    b.putInt("bamper1_fisikkiri", var_cbBamper1_fisikkiri);
                    b.putInt("bamper2_fisikkiri", var_cbBamper2_fisikkiri);
                    b.putInt("fenderblk1_fisikkiri", var_cbFenderblk1_fisikkiri);
                    b.putInt("fenderblk2_fisikkiri", var_cbFenderblk2_fisikkiri);
                    b.putInt("spion1_fisikkiri", var_cbSpion1_fisikkiri);
                    b.putInt("spion2_fisikkiri", var_cbSpion2_fisikkiri);
                    b.putInt("emblem1_fisikkiri", var_cbEmblem1_fisikkiri);
                    b.putInt("emblem2_fisikkiri", var_cbEmblem2_fisikkiri);
                    b.putInt("ban_fisikkiri", var_rbBan_fisikkiri);
                    b.putInt("ban2_fisikkiri", var_cbBan1_fisikkiri);
                    b.putInt("velgstandard_fisikkiri", var_rbVelgstandard_fisikkiri);
                    b.putInt("velgracing_fisikkiri", var_rbVelgracing_fisikkiri);
                    b.putInt("velg1_fisikkiri", var_cbVelg1_fisikkiri);
                    b.putInt("velg2_fisikkiri", var_cbVelg2_fisikkiri);
                    b.putInt("dop1_fisikkiri", var_cbDop1_fisikkiri);
                    b.putInt("dop2_fisikkiri", var_cbDop2_fisikkiri);
                    b.putInt("dopblk1_fisikkiri", var_cbDopBlk1_fisikkiri);
                    b.putInt("dopblk2_fisikkiri", var_cbDopBlk2_fisikkiri);

                    b.putInt("spoiler1_fisikblkg", var_cbSpoiler1_fisikblkg);
                    b.putInt("spoiler2_fisikblkg", var_cbSpoiler2_fisikblkg);
                    b.putInt("lampu1_fisikblkg", var_cbLampu1_fisikblkg);
                    b.putInt("lampu2_fisikblkg", var_cbLampu2_fisikblkg);
                    b.putInt("lampusen1_fisikblkg", var_cbLampusen1_fisikblkg);
                    b.putInt("lampusen2_fisikblkg", var_cbLampusen2_fisikblkg);
                    b.putInt("bamper1_fisikblkg", var_cbBamper1_fisikblkg);
                    b.putInt("bamper2_fisikblkg", var_cbBamper2_fisikblkg);
                    b.putInt("emblem1_fisikblkg", var_cbEmblem1_fisikblkg);
                    b.putInt("emblem2_fisikblkg", var_cbEmblem2_fisikblkg);
                    b.putInt("knalpot1_fisikblkg", var_cbKnalpot1_fisikblkg);
                    b.putInt("knalpot2_fisikblkg", var_cbKnalpot2_fisikblkg);

                    b.putInt("foot1_fisikkanan", var_cbFoot1_fisikkanan);
                    b.putInt("foot2_fisikkanan", var_cbFoot2_fisikkanan);
                    b.putInt("pintudpn1_fisikkanan", var_cbPintudpn1_fisikkanan);
                    b.putInt("pintudpn2_fisikkanan", var_cbPintudpn2_fisikkanan);
                    b.putInt("pintublk1_fisikkanan", var_cbPintublk1_fisikkanan);
                    b.putInt("pintublk2_fisikkanan", var_cbPintublk2_fisikkanan);
                    b.putInt("bamper1_fisikkanan", var_cbBamper1_fisikkanan);
                    b.putInt("bamper2_fisikkanan", var_cbBamper2_fisikkanan);
                    b.putInt("fenderblk1_fisikkanan", var_cbFenderblk1_fisikkanan);
                    b.putInt("fenderblk2_fisikkanan", var_cbFenderblk2_fisikkanan);
                    b.putInt("spion1_fisikkanan", var_cbSpion1_fisikkanan);
                    b.putInt("spion2_fisikkanan", var_cbSpion2_fisikkanan);
                    b.putInt("emblem1_fisikkanan", var_cbEmblem1_fisikkanan);
                    b.putInt("emblem2_fisikkanan", var_cbEmblem2_fisikkanan);
                    b.putInt("ban_fisikkanan", var_rbBan_fisikkanan);
                    b.putInt("ban2_fisikkanan", var_cbBan1_fisikkanan);
//                b.putInt("velg_fisikkanan", var_cbKnalpot2_fisikblkg);
                    b.putInt("velg1_fisikkanan", var_cbVelg1_fisikkanan);
                    b.putInt("velg2_fisikkanan", var_cbVelg2_fisikkanan);
                    b.putInt("dop1_fisikkanan", var_cbDop1_fisikkanan);
                    b.putInt("dop2_fisikkanan", var_cbDop2_fisikkanan);

                    b.putInt("kunciktk1_perlengkapan", var_cbKunciktk1_perlengkapan);
                    b.putInt("kunciktk2_perlengkapan", var_cbKunciktk2_perlengkapan);
                    b.putInt("spion1_perlengkapan", var_cbSpion1_perlengkapan);
                    b.putInt("spion2_perlengkapan", var_cbSpion2_perlengkapan);
                    b.putInt("jok1_perlengkapan", var_cbJok1_perlengkapan);
                    b.putInt("jok2_perlengkapan", var_cbJok2_perlengkapan);
                    b.putInt("sarung1_perlengkapan", var_cbSarung1_perlengkapan);
                    b.putInt("sarung2_perlengkapan", var_cbSarung2_perlengkapan);
                    b.putInt("sandaran1_perlengkapan", var_cbSandaran1_perlengkapan);
                    b.putInt("sandaran2_perlengkapan", var_cbSandaran2_perlengkapan);
                    b.putInt("karpet1_perlengkapan", var_cbKarpet1_perlengkapan);
                    b.putInt("karpet2_perlengkapan", var_cbKarpet2_perlengkapan);
                    b.putInt("pelindung1_perlengkapan", var_cbPelindung1_perlengkapan);
                    b.putInt("pelindung2_perlengkapan", var_cbPelindung2_perlengkapan);
                    b.putInt("segitiga1_perlengkapan", var_cbSegitiga1_perlengkapan);
                    b.putInt("segitiga2_perlengkapan", var_cbSegitiga2_perlengkapan);
                    b.putInt("tool1_perlengkapan", var_cbTool1_perlengkapan);
                    b.putInt("tool2_perlengkapan", var_cbTool2_perlengkapan);
                    b.putInt("cadangan1_perlengkapan", var_cbCadangan1_perlengkapan);
                    b.putInt("cadangan2_perlengkapan", var_cbCadangan2_perlengkapan);
                    b.putInt("kunciban1_perlengkapan", var_cbKunciban1_perlengkapan);
                    b.putInt("kunciban2_perlengkapan", var_cbKunciban2_perlengkapan);
                    b.putInt("dongkrak1_perlengkapan", var_cbDongkrak1_perlengkapan);
                    b.putInt("dongkrak2_perlengkapan", var_cbDongkrak2_perlengkapan);
                    b.putInt("antena1_perlengkapan", var_cbAntena1_perlengkapan);
                    b.putInt("antena2_perlengkapan", var_cbAntena2_perlengkapan);
                    b.putInt("airbag1_perlengkapan", var_cbAirbag1_perlengkapan);
                    b.putInt("airbag2_perlengkapan", var_cbAirbag2_perlengkapan);

                    b.putInt("lampukbt1_listrik", var_cbLampukbt1_listrik);
                    b.putInt("lampukbt2_listrik", var_cbLampukbt2_listrik);
                    b.putInt("wiperkacadpn1_listrik", var_cbWiperkacadpn1_listrik);
                    b.putInt("wiperkacadpn2_listrik", var_cbWiperkacadpn2_listrik);
                    b.putInt("wiperkacablk1_listrik", var_cbWiperkacablk1_listrik);
                    b.putInt("wiperkacablk2_listrik", var_cbWiperkacablk2_listrik);
                    b.putInt("klakson1_listrik", var_cbKlakson1_listrik);
                    b.putInt("klakson2_listrik", var_cbKlakson2_listrik);
                    b.putInt("alarm1_listrik", var_cbAlarm1_listrik);
                    b.putInt("alarm2_listrik", var_cbAlarm2_listrik);
                    b.putInt("jam1_listrik", var_cbJam1_listrik);
                    b.putInt("jam2_listrik", var_cbJam2_listrik);
                    b.putInt("lighter1_listrik", var_cbLighter1_listrik);
                    b.putInt("lighter2_listrik", var_cbLighter2_listrik);
                    b.putInt("radio_listrik", var_rbRadio_listrik);
                    b.putInt("radio1_listrik", var_cbRadio1_listrik);
                    b.putInt("radio2_listrik", var_cbRadio2_listrik);
                    b.putInt("powersup1_listrik", var_cbPowersup1_listrik);
                    b.putInt("powersup2_listrik", var_cbPowersup2_listrik);
                    b.putInt("speaker1_listrik", var_cbSpeaker1_listrik);
                    b.putInt("speaker2_listrik", var_cbSpeaker2_listrik);
                    b.putInt("ac1_listrik", var_cbAc1_listrik);
                    b.putInt("ac2_listrik", var_cbAc2_listrik);
                    b.putInt("powerwin1_listrik", var_cbPowerwin1_listrik);
                    b.putInt("powerwin2_listrik", var_cbPowerwin2_listrik);
                    b.putInt("central1_listrik", var_cbCentral1_listrik);
                    b.putInt("central2_listrik", var_cbCentral2_listrik);
                    b.putInt("remote1_listrik", var_cbRemote1_listrik);
                    b.putInt("remote2_listrik", var_cbRemote2_listrik);
                    b.putInt("speedo1_listrik", var_cbSpeedo1_listrik);
                    b.putInt("speedo2_listrik", var_cbSpeedo2_listrik);
                    b.putInt("odometer1_listrik", var_cbOdometer1_listrik);
                    b.putInt("odometer2_listrik", var_cbOdometer2_listrik);
                    b.putInt("tacho1_listrik", var_cbTacho1_listrik);
                    b.putInt("tacho2_listrik", var_cbTacho2_listrik);
                    b.putInt("accu1_listrik", var_cbAccu1_listrik);
                    b.putInt("accu2_listrik", var_cbAccu2_listrik);

                    b.putInt("mesin1_lain", var_cbMesin1_lain);
                    b.putInt("mesin2_lain", var_cbMesin2_lain);
                    b.putInt("hidraulik1_lain", var_cbHidraulik1_lain);
                    b.putInt("hidraulik2_lain", var_cbHidraulik2_lain);
                    b.putInt("gardan1_lain", var_cbGardan1_lain);
                    b.putInt("gardan2_lain", var_cbGardan2_lain);
                    b.putInt("as1_lain", var_cbAs1_lain);
                    b.putInt("as2_lain", var_cbAs2_lain);
                    b.putInt("bak1_lain", var_cbBak1_lain);
                    b.putInt("bak2_lain", var_cbBak2_lain);
                    b.putInt("stnk1_lain", var_cbStnk1_lain);
                    b.putInt("stnk2_lain", var_cbStnk2_lain);
                    b.putString("stnk_lain", var_etStnk);
                    b.putInt("bukukir1_lain", var_cbBukukir1_lain);
                    b.putInt("bukukir2_lain", var_cbBukukir2_lain);
                    b.putString("bukukir_lain", var_etBukukir);
                    b.putInt("trayek1_lain", var_cbTrayek1_lain);
                    b.putInt("trayek2_lain", var_cbTrayek2_lain);
                    b.putString("ijintrayek_lain", var_etTrayek);
                    b.putInt("usaha1_lain", var_cbUsaha1_lain);
                    b.putInt("usaha2_lain", var_cbUsaha2_lain);
                    b.putString("ijinusaha_lain", var_etUsaha);
                    b.putInt("bukumnl1_lain", var_cbBukumnl1_lain);
                    b.putInt("bukumnl2_lain", var_cbBukumnl2_lain);

                    b.putString("picpenarikan_diterima", var_picPenarikanDiterima);
                    b.putString("picpenarikan", var_picPenarikan);
                    b.putString("picpenyimpanan", var_picPenyimpanan);
                    b.putString("picpenjualan", var_picPenjualan);
                    b.putString("picpengiriman", var_picpengiriman);

                    b.putString("note_picpenarikan", var_note_picpenarikan);
                    b.putString("note_picpenyimpanan", var_note_picpenyimpanan);
                    b.putString("note_picpengiriman", var_note_picpengiriman);

                    b.putString("img1", var_img1);
                    b.putString("img2", var_img2);
                    b.putString("img3", var_img3);
                    b.putString("img4", var_img4);
                    b.putString("img5", var_img5);
                    b.putString("img6", var_img6);
                    b.putString("img7", var_img7);
                    b.putString("img8", var_img8);
                    b.putString("img9", var_img9);
                    b.putString("img10", var_img10);
                    b.putString("img11", var_img11);
                    b.putString("img12", var_img12);
                    b.putString("img13", var_img13);
                    b.putString("img14", var_img14);
                    b.putString("nopol",nopol);

                    i.putExtras(b);
                    startActivity(i);
                }
            }
        });

    }

    private void getBastk(){
        class GetBastk extends AsyncTask<Void,Void,String> {
            ProgressDialog loading;
            @Override
            protected void onPreExecute() {
                super.onPreExecute();
                loading = ProgressDialog.show(TaksasiCekFormActivity.this,"","Loading...",false,false);
            }
            @Override
            protected void onPostExecute(String s) {
                super.onPostExecute(s);
                loading.dismiss();
                showData(s);
            }
            @SuppressLint("WrongThread")
            @Override
            protected String doInBackground(Void... params) {
                HashMap<String,String> hashMap = new HashMap<>();
                hashMap.put(configuration.KEY_APPID,appid);
                hashMap.put(configuration.KEY_CCODE,ccode);
                hashMap.put(configuration.KEY_USERNAME,_name);
                hashMap.put(configuration.KEY_TOKEN,_token);
                hashMap.put(configuration.KEY_PARENT,"2");
                hashMap.put(configuration.KEY_NOPOL,nopol);
                RequestHandler rh = new RequestHandler();

                String s = rh.sendPostRequest(configuration.URL_DETAIL_BASTK,hashMap);
                Log.wtf("kirim", s);
                return s;
            }
        }
        GetBastk ge = new GetBastk();
        ge.execute();
    }
    private void showData(String json){
        try {
            JSONObject jsonObject = new JSONObject(json);
            code = jsonObject.getInt(configuration.TAG_CODE);
            message = jsonObject.getString(configuration.TAG_MESSAGE);
            JSONArray result = jsonObject.getJSONArray(configuration.TAG_JSON_DATA);
            JSONObject user = result.getJSONObject(0);
            Log.d("TAG-user", "showData: " + user);
            vehicle_id = user.getString(configuration.KEY_VEHICLEID);
            vhc_type_name = user.getString(configuration.KEY_VHC_TYPE);
            vehicle_year = user.getString(configuration.KEY_VHC_YEAR);
            vehicle_color = user.getString(configuration.KEY_VHC_COLOR);
            vehicle_engine_no = user.getString(configuration.KEY_VHC_ENGINE);
            vehicle_chasis_no = user.getString(configuration.KEY_VHC_CHASIS);
            vhc_loc_penarikan = user.getString(configuration.KEY_VHC_PENARIKAN);
            vhc_loc_pool = user.getString(configuration.KEY_LOC_POOL);
            vhc_date_in = user.getString(configuration.KEY_VHC_DATE);
            vhc_stnk = user.getString(configuration.KEY_VHC_STNK);
            vhc_kmditarik = user.getString(configuration.KEY_KM_DITARIK);
            vhc_kmditerima = user.getString(configuration.KEY_VHC_DITERIMA);
            vhc_meterbensin = user.getString(configuration.KEY_METER_BENSIN);
            vhc_cabang = user.getString(configuration.KEY_VHC_CABANG);
            vendor_name = user.getString(configuration.KEY_VENDOR_NAME);
            pool = user.getString(configuration.KEY_POOL);
            vhc_cat_name = user.getString(configuration.KEY_VHC_CAT);

            if (vhc_cat_name.equals("MTR")){
                //================= Variable Ceklist ======================================
                var_cover_kepala1 = user.getInt(configuration.MOBMOTOR_cover_kepala1);
                var_cover_kepala2 = user.getInt(configuration.MOBMOTOR_cover_kepala2);
                var_cover_speedo1 = user.getInt(configuration.MOBMOTOR_cover_speedo1);
                var_cover_speedo2 = user.getInt(configuration.MOBMOTOR_cover_speedo2);
                var_cover_depan1 = user.getInt(configuration.MOBMOTOR_cover_depan1);
                var_cover_depan2 = user.getInt(configuration.MOBMOTOR_cover_depan2);
                var_sayap_kanan1 = user.getInt(configuration.MOBMOTOR_sayap_kanan1);
                var_sayap_kanan2 = user.getInt(configuration.MOBMOTOR_sayap_kanan2);
                var_sayap_kiri1 = user.getInt(configuration.MOBMOTOR_sayap_kiri1);
                var_sayap_kiri2 = user.getInt(configuration.MOBMOTOR_sayap_kiri2);
                var_spak_depan1 = user.getInt(configuration.MOBMOTOR_spak_depan1);
                var_spak_depan2 = user.getInt(configuration.MOBMOTOR_spak_depan2);

                var_cover_tengah1 = user.getInt(configuration.MOBMOTOR_cover_tengah1);
                var_cover_tengah2 = user.getInt(configuration.MOBMOTOR_cover_tengah2);
                var_cover_spgkanan1 = user.getInt(configuration.MOBMOTOR_cover_spgkanan1);
                var_cover_spgkanan2 = user.getInt(configuration.MOBMOTOR_cover_spgkanan2);
                var_cover_spgkiri1 = user.getInt(configuration.MOBMOTOR_cover_spgkiri1);
                var_cover_spgkiri2 = user.getInt(configuration.MOBMOTOR_cover_spgkiri2);
                var_rantai_depan1 = user.getInt(configuration.MOBMOTOR_rantai_depan1);
                var_rantai_depan2 = user.getInt(configuration.MOBMOTOR_rantai_depan2);

                var_rantai_blkg1 = user.getInt(configuration.MOBMOTOR_rantai_blkg1);
                var_rantai_blkg2 = user.getInt(configuration.MOBMOTOR_rantai_blkg2);

                var_spak_blkg1 = user.getInt(configuration.MOBMOTOR_spak_blkg1);
                var_spak_blkg2 = user.getInt(configuration.MOBMOTOR_spak_blkg2);
                var_cover_accu1 = user.getInt(configuration.MOBMOTOR_cover_accu1);
                var_cover_accu2 = user.getInt(configuration.MOBMOTOR_cover_accu2);
                var_cover_lampurem1 = user.getInt(configuration.MOBMOTOR_cover_lampurem1);
                var_cover_lampurem2 = user.getInt(configuration.MOBMOTOR_cover_lampurem2);
                var_tangki_bensin1 = user.getInt(configuration.MOBMOTOR_tangki_bensin1);
                var_tangki_bensin2 = user.getInt(configuration.MOBMOTOR_tangki_bensin2);
                var_cover_bawah1 = user.getInt(configuration.MOBMOTOR_cover_bawah1);
                var_cover_bawah2 = user.getInt(configuration.MOBMOTOR_cover_bawah2);
                var_dek_desk1 = user.getInt(configuration.MOBMOTOR_dek_desk1);
                var_dek_desk2 = user.getInt(configuration.MOBMOTOR_dek_desk2);
                var_cover_mesin1 = user.getInt(configuration.MOBMOTOR_cover_mesin1);
                var_cover_mesin2 = user.getInt(configuration.MOBMOTOR_cover_mesin2);
                var_emblem1 = user.getInt(configuration.MOBMOTOR_emblem1);
                var_emblem2 = user.getInt(configuration.MOBMOTOR_emblem2);
                var_blok_mesin1 = user.getInt(configuration.MOBMOTOR_blok_mesin1);
                var_blok_mesin2 = user.getInt(configuration.MOBMOTOR_blok_mesin2);
                var_carburator1 = user.getInt(configuration.MOBMOTOR_carburator1);
                var_carburator2 = user.getInt(configuration.MOBMOTOR_carburator2);
                var_filter_carbu1 = user.getInt(configuration.MOBMOTOR_filter_carbu1);
                var_filter_carbu2 = user.getInt(configuration.MOBMOTOR_filter_carbu2);
                var_busi1 = user.getInt(configuration.MOBMOTOR_busi1);
                var_busi2 = user.getInt(configuration.MOBMOTOR_busi2);
                var_cdi1 = user.getInt(configuration.MOBMOTOR_cdi1);
                var_cdi2 = user.getInt(configuration.MOBMOTOR_cdi2);
                var_accu1 = user.getInt(configuration.MOBMOTOR_accu1);
                var_accu2 = user.getInt(configuration.MOBMOTOR_accu2);
                var_kick_starter1 = user.getInt(configuration.MOBMOTOR_kick_starter1);
                var_kick_starter2 = user.getInt(configuration.MOBMOTOR_kick_starter2);
                var_perseneling1 = user.getInt(configuration.MOBMOTOR_perseneling1);
                var_perseneling2 = user.getInt(configuration.MOBMOTOR_perseneling2);

                var_knalpot1 = user.getInt(configuration.MOBMOTOR_knalpot1);
                var_knalpot2 = user.getInt(configuration.MOBMOTOR_knalpot2);
                var_coil1 = user.getInt(configuration.MOBMOTOR_coil1);
                var_coil2 = user.getInt(configuration.MOBMOTOR_coil2);
                var_blok1 = user.getInt(configuration.MOBMOTOR_blok1);
                var_blok2 = user.getInt(configuration.MOBMOTOR_blok2);
                var_tutupcvt1 = user.getInt(configuration.MOBMOTOR_tutupcvt1);
                var_tutupcvt2 = user.getInt(configuration.MOBMOTOR_tutupcvt2);
                var_radiator1 = user.getInt(configuration.MOBMOTOR_radiator1);
                var_radiator2 = user.getInt(configuration.MOBMOTOR_radiator2);
                var_lampu_depan1 = user.getInt(configuration.MOBMOTOR_lampu_depan1);
                var_lampu_depan2 = user.getInt(configuration.MOBMOTOR_lampu_depan2);
                var_sein_depan1 = user.getInt(configuration.MOBMOTOR_sein_depan1);
                var_sein_depan2 = user.getInt(configuration.MOBMOTOR_sein_depan2);
                var_sein_blkg1 = user.getInt(configuration.MOBMOTOR_sein_blkg1);
                var_sein_blkg2 = user.getInt(configuration.MOBMOTOR_sein_blkg2);
                var_lampu_rem1 = user.getInt(configuration.MOBMOTOR_lampu_rem1);
                var_lampu_rem2 = user.getInt(configuration.MOBMOTOR_lampu_rem2);
                var_handlerem_depan1 = user.getInt(configuration.MOBMOTOR_handlerem_depan1);
                var_handlerem_depan2 = user.getInt(configuration.MOBMOTOR_handlerem_depan2);
                var_pedalrem_blkg1 = user.getInt(configuration.MOBMOTOR_pedalrem_blkg1);
                var_pedalrem_blkg2 = user.getInt(configuration.MOBMOTOR_pedalrem_blkg2);
                var_handlerem_blkg1 = user.getInt(configuration.MOBMOTOR_handlerem_blkg1);
                var_handlerem_blkg2 = user.getInt(configuration.MOBMOTOR_handlerem_blkg2);
                var_handle_kopling1 = user.getInt(configuration.MOBMOTOR_handle_kopling1);
                var_handle_kopling2 = user.getInt(configuration.MOBMOTOR_handle_kopling2);
                var_master_rem1 = user.getInt(configuration.MOBMOTOR_master_rem1);
                var_master_rem2 = user.getInt(configuration.MOBMOTOR_master_rem2);
                var_caliper1 = user.getInt(configuration.MOBMOTOR_caliper1);
                var_caliper2 = user.getInt(configuration.MOBMOTOR_caliper2);
                var_cakram1 = user.getInt(configuration.MOBMOTOR_cakram1);
                var_cakram2 = user.getInt(configuration.MOBMOTOR_cakram2);
                var_shock_depan1 = user.getInt(configuration.MOBMOTOR_shock_depan1);
                var_shock_depan2 = user.getInt(configuration.MOBMOTOR_shock_depan2);
                var_shock_blkg1 = user.getInt(configuration.MOBMOTOR_shock_blkg1);
                var_shock_blkg2 = user.getInt(configuration.MOBMOTOR_shock_blkg2);
                var_tromol_depan1 = user.getInt(configuration.MOBMOTOR_tromol_depan1);
                var_tromol_depan2 = user.getInt(configuration.MOBMOTOR_tromol_depan2);
                var_tromol_blkg1 = user.getInt(configuration.MOBMOTOR_tromol_blkg1);
                var_tromol_blkg2 = user.getInt(configuration.MOBMOTOR_tromol_blkg2);
                var_footstep_depan1 = user.getInt(configuration.MOBMOTOR_footstep_depan1);
                var_footstep_depan2 = user.getInt(configuration.MOBMOTOR_footstep_depan2);
                var_footstep_blkg1 = user.getInt(configuration.MOBMOTOR_footstep_blkg1);
                var_footstep_blkg2 = user.getInt(configuration.MOBMOTOR_footstep_blkg2);
                var_swing_arm1 = user.getInt(configuration.MOBMOTOR_swing_arm1);
                var_swing_arm2 = user.getInt(configuration.MOBMOTOR_swing_arm2);
                var_rantai_fanbelt1 = user.getInt(configuration.MOBMOTOR_rantai_fanbelt1);
                var_rantai_fanbelt2 = user.getInt(configuration.MOBMOTOR_rantai_fanbelt2);
                var_gear_depan1 = user.getInt(configuration.MOBMOTOR_gear_depan1);
                var_gear_depan2 = user.getInt(configuration.MOBMOTOR_gear_depan2);
                var_gear_blkg1 = user.getInt(configuration.MOBMOTOR_gear_blkg1);
                var_gear_blkg2 = user.getInt(configuration.MOBMOTOR_gear_blkg2);
                var_standar_tengah1 = user.getInt(configuration.MOBMOTOR_standar_tengah1);
                var_standar_tengah2 = user.getInt(configuration.MOBMOTOR_standar_tengah2);
                var_standar_samping1 = user.getInt(configuration.MOBMOTOR_standar_samping1);
                var_standar_samping2 = user.getInt(configuration.MOBMOTOR_standar_samping2);
                var_ban_depan1 = user.getInt(configuration.MOBMOTOR_ban_depan1);
                var_ban_depan2 = user.getInt(configuration.MOBMOTOR_ban_depan2);
                var_ban_blkg1 = user.getInt(configuration.MOBMOTOR_ban_blkg1);
                var_ban_blkg2 = user.getInt(configuration.MOBMOTOR_ban_blkg2);
                var_velg_depan1 = user.getInt(configuration.MOBMOTOR_velg_depan1);
                var_velg_depan2 = user.getInt(configuration.MOBMOTOR_velg_depan2);
                var_velg_blkg1 = user.getInt(configuration.MOBMOTOR_velg_blkg1);
                var_velg_blkg2 = user.getInt(configuration.MOBMOTOR_velg_blkg2);
                var_kaca_spion1 = user.getInt(configuration.MOBMOTOR_kaca_spion1);
                var_kaca_spion2 = user.getInt(configuration.MOBMOTOR_kaca_spion2);
                var_speedometer1 = user.getInt(configuration.MOBMOTOR_speedometer1);
                var_speedometer2 = user.getInt(configuration.MOBMOTOR_speedometer2);
                var_grip_stang1 = user.getInt(configuration.MOBMOTOR_Grip_stang1);
                var_grip_stang2 = user.getInt(configuration.MOBMOTOR_Grip_stang2);
                var_rumah_kunci1 = user.getInt(configuration.MOBMOTOR_Rumah_kunci1);
                var_rumah_kunci2 = user.getInt(configuration.MOBMOTOR_Rumah_kunci2);
                var_klakson1 = user.getInt(configuration.MOBMOTOR_Klakson1);
                var_klakson2 = user.getInt(configuration.MOBMOTOR_Klakson2);
                var_behel1 = user.getInt(configuration.MOBMOTOR_Behel1);
                var_behel2 = user.getInt(configuration.MOBMOTOR_Behel2);
                var_tutup_knalpot1 = user.getInt(configuration.MOBMOTOR_Tutup_knalpot1);
                var_tutup_knalpot2 = user.getInt(configuration.MOBMOTOR_Tutup_knalpot2);
                var_jok1 = user.getInt(configuration.MOBMOTOR_jok1);
                var_jok2 = user.getInt(configuration.MOBMOTOR_jok1);
                var_stripping1 = user.getInt(configuration.MOBMOTOR_Stripping1);
                var_stripping2 = user.getInt(configuration.MOBMOTOR_Stripping2);
                var_tombol_navigasi1 = user.getInt(configuration.MOBMOTOR_Tombol_navigasi1);
                var_tombol_navigasi2 = user.getInt(configuration.MOBMOTOR_Tombol_navigasi2);
                var_etStnk = user.getString(configuration.KEY_stnk_lain);
                var_cbStnk1_lain = user.getInt(configuration.KEY_stnk1_lain);
                var_cbStnk2_lain = user.getInt(configuration.KEY_stnk2_lain);
                var_cbBukumnl1_lain = user.getInt(configuration.KEY_bukumnl1_lain);
                var_cbBukumnl2_lain = user.getInt(configuration.KEY_bukumnl2_lain);
            }else{
                //================= Variable Ceklist ======================================
                var_cbGrill1_fisikmuka = user.getInt(configuration.KEY_grill1_fisikmuka);
                var_cbGrill2_fisikmuka = user.getInt(configuration.KEY_grill2_fisikmuka);
                var_cbLampu1_fisikmuka = user.getInt(configuration.KEY_lampu1_fisikmuka);
                var_cbLampu2_fisikmuka = user.getInt(configuration.KEY_lampu2_fisikmuka);
                var_cbLampusen1_fisikmuka = user.getInt(configuration.KEY_lampusen1_fisikmuka);
                var_cbLampusen2_fisikmuka = user.getInt(configuration.KEY_lampusen2_fisikmuka);
                var_cbBamper1_fisikmuka = user.getInt(configuration.KEY_bamper1_fisikmuka);
                var_cbBamper2_fisikmuka = user.getInt(configuration.KEY_bamper2_fisikmuka);
                var_cbEmblem1_fisikmuka = user.getInt(configuration.KEY_emblem1_fisikmuka);
                var_cbEmblem2_fisikmuka = user.getInt(configuration.KEY_emblem2_fisikmuka);
                var_cbTanduk1_fisikmuka = user.getInt(configuration.KEY_tanduk1_fisikmuka);
                var_cbTanduk2_fisikmuka = user.getInt(configuration.KEY_tanduk2_fisikmuka);

                var_cbFootstep1_fisikkiri = user.getInt(configuration.KEY_footstep1_fisikkiri);
                var_cbFootstep2_fisikkiri = user.getInt(configuration.KEY_footstep2_fisikkiri);
                var_cbPintudpn1_fisikkiri = user.getInt(configuration.KEY_pintudpn1_fisikkiri);
                var_cbPintudpn2_fisikkiri = user.getInt(configuration.KEY_pintudpn2_fisikkiri);
                var_cbPintublk1_fisikkiri = user.getInt(configuration.KEY_pintublk1_fisikkiri);
                var_cbPintublk2_fisikkiri = user.getInt(configuration.KEY_pintublk2_fisikkiri);
                var_cbBamper1_fisikkiri = user.getInt(configuration.KEY_bamper1_fisikkiri);
                var_cbBamper2_fisikkiri = user.getInt(configuration.KEY_bamper2_fisikkiri);
                var_cbFenderblk1_fisikkiri = user.getInt(configuration.KEY_fenderblk1_fisikkiri);
                var_cbFenderblk2_fisikkiri = user.getInt(configuration.KEY_fenderblk2_fisikkiri);
                var_cbSpion1_fisikkiri = user.getInt(configuration.KEY_spion1_fisikkiri);
                var_cbSpion2_fisikkiri = user.getInt(configuration.KEY_spion2_fisikkiri);
                var_cbEmblem1_fisikkiri = user.getInt(configuration.KEY_emblem1_fisikkiri);
                var_cbEmblem2_fisikkiri = user.getInt(configuration.KEY_emblem2_fisikkiri);
//            var_rbBan_fisikkiri = user.getInt(configuration.KEY_ban_fisikkiri);
                var_cbBan1_fisikkiri = user.getInt(configuration.KEY_ban2_fisikkiri);

                var_rbVelgstandard_fisikkiri = user.getInt(configuration.KEY_velgstandard_fisikkiri);
                var_rbVelgracing_fisikkiri = user.getInt(configuration.KEY_velgracing_fisikkiri);
                var_cbVelg1_fisikkiri = user.getInt(configuration.KEY_velg1_fisikkiri);
                var_cbVelg2_fisikkiri = user.getInt(configuration.KEY_velg2_fisikkiri);
                var_cbDop1_fisikkiri = user.getInt(configuration.KEY_dop1_fisikkiri);
                var_cbDop2_fisikkiri = user.getInt(configuration.KEY_dop2_fisikkiri);
//            var_cbDopBlk1_fisikkiri = user.getInt(configuration.KEY_dopblk1_fisikkiri);
//            var_cbDopBlk2_fisikkiri = user.getInt(configuration.KEY_dopblk2_fisikkiri);

                var_cbSpoiler1_fisikblkg = user.getInt(configuration.KEY_spoiler1_fisikblkg);
                var_cbSpoiler2_fisikblkg = user.getInt(configuration.KEY_spoiler2_fisikblkg);
                var_cbLampu1_fisikblkg = user.getInt(configuration.KEY_lampu1_fisikblkg);
                var_cbLampu2_fisikblkg = user.getInt(configuration.KEY_lampu2_fisikblkg);
                var_cbLampusen1_fisikblkg = user.getInt(configuration.KEY_lampusen1_fisikblkg);
//
//
                var_cbLampusen2_fisikblkg = user.getInt(configuration.KEY_lampusen2_fisikblkg);
                var_cbBamper1_fisikblkg = user.getInt(configuration.KEY_bamper1_fisikblkg);
                var_cbBamper2_fisikblkg = user.getInt(configuration.KEY_bamper2_fisikblkg);
                var_cbEmblem1_fisikblkg = user.getInt(configuration.KEY_emblem1_fisikblkg);
                var_cbEmblem2_fisikblkg = user.getInt(configuration.KEY_emblem2_fisikblkg);
                var_cbKnalpot1_fisikblkg = user.getInt(configuration.KEY_knalpot1_fisikblkg);
                var_cbKnalpot2_fisikblkg = user.getInt(configuration.KEY_knalpot2_fisikblkg);

                var_cbFoot1_fisikkanan = user.getInt(configuration.KEY_foot1_fisikkanan);
                var_cbFoot2_fisikkanan = user.getInt(configuration.KEY_foot2_fisikkanan);
                var_cbPintudpn1_fisikkanan = user.getInt(configuration.KEY_pintudpn1_fisikkanan);
                var_cbPintudpn2_fisikkanan = user.getInt(configuration.KEY_pintudpn2_fisikkanan);
                var_cbPintublk1_fisikkanan = user.getInt(configuration.KEY_pintublk1_fisikkanan);
                var_cbPintublk2_fisikkanan = user.getInt(configuration.KEY_pintublk2_fisikkanan);
                var_cbBamper1_fisikkanan = user.getInt(configuration.KEY_bamper1_fisikkanan);
                var_cbBamper2_fisikkanan = user.getInt(configuration.KEY_bamper2_fisikkanan);
                var_cbFenderblk1_fisikkanan = user.getInt(configuration.KEY_fenderblk1_fisikkanan);
                var_cbFenderblk2_fisikkanan = user.getInt(configuration.KEY_fenderblk2_fisikkanan);
                var_cbSpion1_fisikkanan = user.getInt(configuration.KEY_spion1_fisikkanan);
                var_cbSpion2_fisikkanan = user.getInt(configuration.KEY_spion2_fisikkanan);
                var_cbEmblem1_fisikkanan = user.getInt(configuration.KEY_emblem1_fisikkanan);
                var_cbEmblem2_fisikkanan = user.getInt(configuration.KEY_emblem2_fisikkanan);
//            var_rbBan_fisikkanan = user.getInt(configuration.KEY_ban_fisikkanan);
//            var_cbBan1_fisikkanan = user.getInt(configuration.KEY_ban2_fisikkanan);
//
                var_cbVelg1_fisikkanan = user.getInt(configuration.KEY_velg1_fisikkanan);
                var_cbVelg2_fisikkanan = user.getInt(configuration.KEY_velg2_fisikkanan);
                var_cbDop1_fisikkanan = user.getInt(configuration.KEY_dop1_fisikkanan);
                var_cbDop2_fisikkanan = user.getInt(configuration.KEY_dop2_fisikkanan);
////            var_cbDopBlk1_fisikkanan = user.getInt(configuration.KEY_tanduk2_fisikmuka);
////            var_cbDopBlk2_fisikkanan = user.getInt(configuration.KEY_tanduk2_fisikmuka);
//
                var_cbKunciktk1_perlengkapan = user.getInt(configuration.KEY_kunciktk1_perlengkapan);
                var_cbKunciktk2_perlengkapan = user.getInt(configuration.KEY_kunciktk2_perlengkapan);
                var_cbSpion1_perlengkapan = user.getInt(configuration.KEY_spion1_perlengkapan);
                var_cbSpion2_perlengkapan = user.getInt(configuration.KEY_spion2_perlengkapan);
                var_cbJok1_perlengkapan = user.getInt(configuration.KEY_jok1_perlengkapan);
                var_cbJok2_perlengkapan = user.getInt(configuration.KEY_jok2_perlengkapan);
                var_cbSarung1_perlengkapan = user.getInt(configuration.KEY_sarung1_perlengkapan);
                var_cbSarung2_perlengkapan = user.getInt(configuration.KEY_sarung2_perlengkapan);
                var_cbSandaran1_perlengkapan = user.getInt(configuration.KEY_sandaran1_perlengkapan);
                var_cbSandaran2_perlengkapan = user.getInt(configuration.KEY_sandaran2_perlengkapan);
                var_cbKarpet1_perlengkapan = user.getInt(configuration.KEY_karpet1_perlengkapan);
                var_cbKarpet2_perlengkapan = user.getInt(configuration.KEY_karpet2_perlengkapan);
                var_cbPelindung1_perlengkapan = user.getInt(configuration.KEY_pelindung1_perlengkapan);
                var_cbPelindung2_perlengkapan = user.getInt(configuration.KEY_pelindung2_perlengkapan);
                var_cbSegitiga1_perlengkapan = user.getInt(configuration.KEY_segitiga1_perlengkapan);
                var_cbSegitiga2_perlengkapan = user.getInt(configuration.KEY_segitiga2_perlengkapan);
                var_cbTool1_perlengkapan = user.getInt(configuration.KEY_tool1_perlengkapan);
                var_cbTool2_perlengkapan = user.getInt(configuration.KEY_tool2_perlengkapan);
                var_cbCadangan1_perlengkapan = user.getInt(configuration.KEY_cadangan1_perlengkapan);
                var_cbCadangan2_perlengkapan = user.getInt(configuration.KEY_cadangan2_perlengkapan);
                var_cbKunciban1_perlengkapan = user.getInt(configuration.KEY_kunciban1_perlengkapan);
                var_cbKunciban2_perlengkapan = user.getInt(configuration.KEY_kunciban2_perlengkapan);
                var_cbDongkrak1_perlengkapan = user.getInt(configuration.KEY_dongkrak1_perlengkapan);
                var_cbDongkrak2_perlengkapan = user.getInt(configuration.KEY_dongkrak2_perlengkapan);
                var_cbAntena1_perlengkapan = user.getInt(configuration.KEY_antena1_perlengkapan);
                var_cbAntena2_perlengkapan = user.getInt(configuration.KEY_antena2_perlengkapan);
                var_cbAirbag1_perlengkapan = user.getInt(configuration.KEY_airbag1_perlengkapan);
                var_cbAirbag2_perlengkapan = user.getInt(configuration.KEY_airbag2_perlengkapan);
//
                var_cbLampukbt1_listrik = user.getInt(configuration.KEY_lampukbt1_listrik);
                var_cbLampukbt2_listrik = user.getInt(configuration.KEY_lampukbt2_listrik);
                var_cbWiperkacadpn1_listrik = user.getInt(configuration.KEY_wiperkacadpn1_listrik);
                var_cbWiperkacadpn2_listrik = user.getInt(configuration.KEY_wiperkacadpn2_listrik);
                var_cbWiperkacablk1_listrik = user.getInt(configuration.KEY_wiperkacablk1_listrik);
                var_cbWiperkacablk2_listrik = user.getInt(configuration.KEY_wiperkacablk2_listrik);
                var_cbKlakson1_listrik = user.getInt(configuration.KEY_klakson1_listrik);
                var_cbKlakson2_listrik = user.getInt(configuration.KEY_klakson2_listrik);
                var_cbAlarm1_listrik = user.getInt(configuration.KEY_alarm1_listrik);
                var_cbAlarm2_listrik = user.getInt(configuration.KEY_alarm2_listrik);
                var_cbJam1_listrik = user.getInt(configuration.KEY_jam1_listrik);
                var_cbJam2_listrik = user.getInt(configuration.KEY_jam2_listrik);
                var_cbLighter1_listrik = user.getInt(configuration.KEY_lighter1_listrik);
                var_cbLighter2_listrik = user.getInt(configuration.KEY_lighter2_listrik);
                var_rbRadio_listrik = user.getInt(configuration.KEY_radio_listrik);
                var_cbRadio1_listrik = user.getInt(configuration.KEY_radio1_listrik);
                var_cbRadio2_listrik = user.getInt(configuration.KEY_radio2_listrik);
                var_cbPowersup1_listrik = user.getInt(configuration.KEY_powersup1_listrik);
                var_cbPowersup2_listrik = user.getInt(configuration.KEY_powersup2_listrik);
                var_cbSpeaker1_listrik = user.getInt(configuration.KEY_speaker1_listrik);
                var_cbSpeaker2_listrik = user.getInt(configuration.KEY_speaker2_listrik);
                var_cbAc1_listrik = user.getInt(configuration.KEY_ac1_listrik);
                var_cbAc2_listrik = user.getInt(configuration.KEY_ac2_listrik);
                var_cbPowerwin1_listrik = user.getInt(configuration.KEY_powerwin1_listrik);
                var_cbPowerwin2_listrik = user.getInt(configuration.KEY_powerwin2_listrik);
                var_cbCentral1_listrik = user.getInt(configuration.KEY_central1_listrik);
                var_cbCentral2_listrik = user.getInt(configuration.KEY_central2_listrik);
                var_cbRemote1_listrik = user.getInt(configuration.KEY_remote1_listrik);
                var_cbRemote2_listrik = user.getInt(configuration.KEY_remote2_listrik);
                var_cbSpeedo1_listrik = user.getInt(configuration.KEY_speedo1_listrik);
                var_cbSpeedo2_listrik = user.getInt(configuration.KEY_speedo2_listrik);
                var_cbOdometer1_listrik = user.getInt(configuration.KEY_odometer1_listrik);
                var_cbOdometer2_listrik = user.getInt(configuration.KEY_odometer2_listrik);
                var_cbTacho1_listrik = user.getInt(configuration.KEY_tacho1_listrik);
                var_cbTacho2_listrik = user.getInt(configuration.KEY_tacho2_listrik);
                var_cbAccu1_listrik = user.getInt(configuration.KEY_accu1_listrik);
                var_cbAccu2_listrik = user.getInt(configuration.KEY_accu2_listrik);
////
                var_cbMesin1_lain = user.getInt(configuration.KEY_mesin1_lain);
                var_cbMesin2_lain = user.getInt(configuration.KEY_mesin2_lain);
                var_cbHidraulik1_lain = user.getInt(configuration.KEY_hidraulik1_lain);
                var_cbHidraulik2_lain = user.getInt(configuration.KEY_hidraulik2_lain);
                var_cbGardan1_lain = user.getInt(configuration.KEY_gardan1_lain);
                var_cbGardan2_lain = user.getInt(configuration.KEY_gardan2_lain);
                var_cbAs1_lain = user.getInt(configuration.KEY_as1_lain);
                var_cbAs2_lain = user.getInt(configuration.KEY_as2_lain);
                var_cbBak1_lain = user.getInt(configuration.KEY_bak1_lain);
                var_cbBak2_lain = user.getInt(configuration.KEY_bak2_lain);
                var_cbStnk1_lain = user.getInt(configuration.KEY_stnk1_lain);
                var_cbStnk2_lain = user.getInt(configuration.KEY_stnk2_lain);
                var_etStnk = user.getString(configuration.KEY_stnk_lain);
                var_cbBukukir1_lain = user.getInt(configuration.KEY_bukukir1_lain);
                var_cbBukukir2_lain = user.getInt(configuration.KEY_bukukir2_lain);
                var_etBukukir = user.getString(configuration.KEY_bukukir_lain);
                var_cbTrayek1_lain = user.getInt(configuration.KEY_trayek1_lain);
                var_cbTrayek2_lain = user.getInt(configuration.KEY_trayek2_lain);
                var_etTrayek = user.getString(configuration.KEY_trayek_lain);
                var_cbUsaha1_lain = user.getInt(configuration.KEY_usaha1_lain);
                var_cbUsaha2_lain = user.getInt(configuration.KEY_usaha2_lain);
                var_etUsaha = user.getString(configuration.KEY_usaha_lain);
                var_cbBukumnl1_lain = user.getInt(configuration.KEY_bukumnl1_lain);
                var_cbBukumnl2_lain = user.getInt(configuration.KEY_bukumnl2_lain);
            }


            var_picPenarikanDiterima = user.getString(configuration.KEY_picPenarikanDiterima);
            var_picPenarikan = user.getString(configuration.KEY_picPenarikan);
            var_picPenyimpanan = user.getString(configuration.KEY_picPenyimpanan);
            var_picPenjualan = user.getString(configuration.KEY_picPenjualan);
            var_picpengiriman = user.getString(configuration.KEY_picPengiriman);

            var_note_picpenarikan = user.getString(configuration.KEY_note_picPengiriman);
            var_note_picpengiriman = user.getString(configuration.KEY_note_picPengiriman);
            var_note_picpenyimpanan = user.getString(configuration.KEY_note_picPenyimpanan);

            var_img1 = user.getString(configuration.KEY_img1);
            var_img2 = user.getString(configuration.KEY_img2);
            var_img3 = user.getString(configuration.KEY_img3);
            var_img4 = user.getString(configuration.KEY_img4);
            var_img5 = user.getString(configuration.KEY_img5);
            var_img6 = user.getString(configuration.KEY_img6);
            var_img7 = user.getString(configuration.KEY_img7);
            var_img8 = user.getString(configuration.KEY_img8);
            var_img9 = user.getString(configuration.KEY_img9);
            var_img10 = user.getString(configuration.KEY_img10);
            var_img11 = user.getString(configuration.KEY_img11);
            var_img12 = user.getString(configuration.KEY_img12);
            var_img13 = user.getString(configuration.KEY_img13);
            var_img14 = user.getString(configuration.KEY_img14);

        } catch (JSONException e) {
            e.printStackTrace();
//            Toast.makeText(BpCekFormActivity.this,"catch",Toast.LENGTH_LONG).show();
        }

        if(code == 200){
            String[] tgl = vhc_date_in.split(" ");
            etTanggal.setText(tgl[0]);
            etPukul.setText(tgl[1]);
            etMerk.setText(vhc_type_name);
            etTahun.setText(vehicle_year);
            etStnk_an.setText(vhc_stnk);
            String[] vehicle = vehicle_id.split("-");
            etNopol1.setText(vehicle[0]);
            etNopol2.setText(vehicle[1]);
            etNopol3.setText(vehicle[2]);
            etKmditarik.setText(vhc_kmditarik);
            etMeterbensin.setText(vhc_meterbensin);
            etCabang.setText(vhc_cabang);
            etNomesin.setText(vehicle_engine_no);
            etNorangka.setText(vehicle_chasis_no);
            etWarna.setText(vehicle_color);
            etKmditerima.setText(vhc_kmditerima);
            etVendor.setText(vendor_name);
            etLokasipool.setText(pool);
            etTypeunit.setText(vhc_cat_name);



        }else if (code == 304){
            Toast.makeText(this, message, Toast.LENGTH_SHORT).show();
        }else {
            Toast.makeText(this, message, Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();
        switch (id){
            case android.R.id.home:
                this.finish();
                overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right);
        }
        return super.onOptionsItemSelected(item);
    }

    @Override
    public void onBackPressed() {
        super.onBackPressed();
        overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right);

    }
}
